### ISSUE TITLE
Use a GitHub Actions workflow to automate updating colorschemes from upstream

### ISSUE THREAD

**Issue by fnune** [twnaing/base16-luakit#1]
I added this to my repository:

https://github.com/fnune/base16-fzf/blob/master/.github/workflows/update.yml

It updates it automatically every week with changes from upstream.

```yaml
name: Update the repository with the latest base16 colorschemes
on:
  schedule:
    - cron: "0 0 * * 0" # https://crontab.guru/every-week
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install pybase16
        run: pip install pybase16-builder
      - name: Fetch the repository code
        uses: actions/checkout@v2
      - name: Run make
        run: make
      - name: Commit the changes, if any
        uses: stefanzweifel/git-auto-commit-action@v4.1.1
        with:
          commit_message: Update repository with the latest base16 colorschemes
          branch: ${{ github.head_ref }}
```

Made this issue because I noticed your project uses `pybase16-builder` and has a `Makefile` too. Just a suggestion :)
